# Generated by Django 5.0.6 on 2024-06-25 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateField(auto_now=True)),
                ('BankAccountNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.bankaccount')),
            ],
        ),
    ]
