# Generated by Django 5.0.6 on 2024-06-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_paymentdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='Manager_account',
        ),
    ]
