# Generated by Django 5.0.6 on 2024-06-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_bankaccount_manager_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='ammountchal',
            field=models.FloatField(default=0.0),
        ),
    ]
