# Generated by Django 5.0.6 on 2024-06-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_paymentdetail_ammountchal'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
