# Generated by Django 5.0.6 on 2024-06-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_notification_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='seen_status',
            field=models.BooleanField(default=False),
        ),
    ]
