# Generated by Django 5.0.6 on 2024-06-26 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0013_customuser_d_customuser_r_customuser_s'),
        ('management', '0007_meal_d_meal_r_meal_s_alter_meal_paid_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='manager',
        ),
        migrations.AddField(
            model_name='meal',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.holteluser'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
