# Generated by Django 5.0.6 on 2024-06-29 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_remove_meal_manager_meal_admin_alter_meal_meal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='rice_ammount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='Bills_Account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.bills'),
        ),
    ]
