# Generated by Django 5.0.6 on 2024-06-29 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0013_customuser_d_customuser_r_customuser_s'),
        ('management', '0009_bills_rice_ammount_paymentdetail_bills_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='hostel_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Accounts.holteluser'),
        ),
    ]
