# Generated by Django 5.0.6 on 2024-06-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_bills_hostel_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
    ]
