# Generated by Django 5.0.6 on 2024-06-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_holtelborder_created_at_holtelborder_update_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holteluser',
            name='search_key',
            field=models.TextField(default='bangladesh'),
        ),
    ]
