# Generated by Django 5.0.6 on 2024-06-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_holteluser_search_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holtelborder',
            name='admin',
            field=models.ForeignKey(on_delete=models.Model, to='Accounts.holteluser'),
        ),
    ]
