# Generated by Django 5.0.6 on 2024-06-22 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_alter_holtelborder_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holtelborder',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Accounts.holteluser'),
        ),
    ]
