# Generated by Django 5.0.6 on 2024-06-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_alter_holtelborder_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='manager_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holtelmanager',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holtelmanager',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
