# Generated by Django 5.0.6 on 2024-06-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_customuser_manager_status_holtelmanager_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holtelborder',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
