# Generated by Django 5.0.6 on 2024-06-25 01:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_holtelborder_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='otp_created_expired',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
