# Generated by Django 5.0.6 on 2024-06-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_alter_customuser_otp_created_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='otp_created_expired',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
