# Generated by Django 5.0.6 on 2024-06-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_alter_customuser_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='D',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='R',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='S',
            field=models.BooleanField(default=True),
        ),
    ]
